### ISSUE TITLE
Archives do not work

### ISSUE THREAD

**Issue by albfan** [mono/mail-archives#1]
All the txt.gz are not there.

We are trying to recover glade-users and glade-devel mail list to our gnome servers

https://github.com/mono/mail-archives/tree/master/glade-users
https://github.com/mono/mail-archives/tree/master/glade-devel

Anyone has the original backup?

**Comment by albfan** [comment]
Original glade issue:

https://gitlab.gnome.org/Infrastructure/Infrastructure/issues/38

**Comment by akoeplinger** [comment]
@duncanmak do we still have the txt.gz for these lists?

**Comment by albfan** [comment]
That would be awesome, let me know!

**Comment by duncanmak** [comment]
@albfan I just committed them:

* glade-devel: https://github.com/mono/mail-archives/commit/5447653003cd5953c1032311100168021ad8a8c0 
* glade-users: https://github.com/mono/mail-archives/commit/0cf760e1864b5508139b24a80acc6f437f9ee9e9

Hopefully the Jekyll will go through and then they should show up.

**Comment by albfan** [comment]
Best news ever!

Many thanks, will update as soon as we get it back to life inside GNOME!

**Comment by albfan** [comment]
I was able to convert archives to mbox!
